version: '3'
services:
  api:
    build:
      context: .
    ports:
      - ${APP_PORT}:3000
    volumes:
      - /app/node_modules
      - .:/app
    command: yarn dev

networks:
  default:
    external:
      name: local
